language: android
android:
  components:
    - build-tools-21.1.2
    - android-15

install:
    - travis_retry sudo apt-get update -qq
    - travis_retry sudo apt-get install ocaml zlib1g-dev libgc-dev -qq
    - travis_retry git clone https://github.com/HaxeFoundation/neko.git ~/neko
    - cd ~/neko && make os=linux -s && sudo make install -s && cd $TRAVIS_BUILD_DIR
    - travis_retry git clone --recursive https://github.com/HaxeFoundation/haxe.git ~/haxe
    - cd ~/haxe && make -s && make tools -s && sudo make install -s && cd $TRAVIS_BUILD_DIR
    - mkdir ~/haxelib && haxelib setup ~/haxelib
    - haxelib install hxjava
    - haxelib install hxLINQ
    - haxelib install tweenx
    - haxelib git hxAnonCls https://github.com/andyli/hxAnonCls.git

script:
    - haxe build.hxml
    - ant debug